FROM tensorflow/tensorflow:latest-gpu

ADD ./artifacts /artifacts

RUN pip install tensorflow_addons
RUN pip install artifacts/tensorflow_ctc_ext_beam_search_decoder-0.0.2-cp36-cp36m-linux_x86_64.whl

LABEL maintainer="philipp@rouast.com"
